### ISSUE TITLE
Agregar relacion post - organization - areatype

### ISSUE THREAD

**Issue by godiard** [ConocimientoAbierto/policrowd#10]
Cuando el usuario quiera editar un puesto actual o pasado de un politico, le queremos mostrar un alista de opciones. Sería bueno que si elige un Area y un poder, le podamos mostrar las opciones que conocemos. AreaType ya tiene 'NAT' y 'PRV', tenemos que agregar un tipo para los municipios.
Entonces, si elige el Area "Buenos Aires", sabemos que es del tipo "PRV", al elegir "Poder Ejecutivo", nos va a aparecer Gobernador, Vice, Ministro de Educacion, etc.
Van a haber cargos que no estan cargados, o ministerios que se llaman distinto en distintas provincias, pero no se si tiene sentido tener que cargarlo para cada Area.

Que opinan?

**Comment by martinszy** [comment]
Hay que poder especificar a qué área pertenece el cargo. Si a todo el
areatype o a una específica. Funcionará?

**Comment by godiard** [comment]
Hacerlo por area type es más facil, pero si queremos registrar que la municipalidad de tapalqué tiene un "Secretario de deportes equestres", vamos a tener que agregar otra tabla para especificar la relacion con el area, o agregar un campo area optativo. No se bien como mapea este caso en los modelos de django, hay que explorarlo. Otro problema es como presentarle la carga de estas relaciones a los usuarios, o si solo se van a manejar por importaciones y manejos en la base de datos.

**Comment by martinszy** [comment]
Creo que si lo carga un usuario se puede asumir que el cargo es sólo para
una municipalidad. Luego el admin tiene la posibilidad de convertirlo en un
cargo para todo el área type.... Cómo lo ves?

**Comment by godiard** [comment]
Entonces tenemos que agregar dos tablas, una que relaciona puesto-organizacion-tipoarea, y la otra que relaciona puesto-organizacion-area. 
Es factible, agrega un poco de trabajo.

**Comment by martinszy** [comment]
Si. O podés hacer una sola tabla con una columna de restricciones.
Tipoarea prv, restricción: id,id,id
Si no hay restricción entonces es para todo el tipoarea.
Se entiende?
No se si es mejor.

**Comment by godiard** [comment]
SI, las dos opciones son posibles

**Comment by martinszy** [comment]
En qué quedó esto? Se implementó?

**Comment by cesuarez** [comment]
La forma de agregar un puesto a un político quedó de la siguiente manera:
- Se elige un Area de la lista (NAT y PRV mezclados)
- Se puede elegir una sub-area (con tipo MUN) dentro de esa Area elegida (opcional)
- Se elige una organización que esté relacionada el Area seleccionada
- Se elige un Puesto de entre todos los existentes, y si se lo decea, puede seleccionarlo vacío y crear su propio puesto escribiendo en un campo de abajo.
- Se elige la fecha de inicio y fin del puesto.

Muestro una imagen de como se ve esa parte:

![ynr - add post to politician](https://cloud.githubusercontent.com/assets/8973610/14539910/faec1480-0258-11e6-9165-7a5f6b74233c.png)
