### ISSUE TITLE
Faltan los apellidos de los políticos

### ISSUE THREAD

**Issue by martinszy** [ConocimientoAbierto/policrowd#12]
Por ejemplo acá:
http://beta.policrowd.org/person/2286

**Comment by cesuarez** [comment]
Corregido. Revisar

**Comment by martinszy** [comment]
Ahoar lo reviso. Un dato para la próxima: Lo ideal es mencionar el numero de issue en el mensaje de commit, asi aparece acá, en "Esto corrige #12" en el mensaje de commit, y luego es más fácil de ubicarlo para revisar.

**Comment by martinszy** [comment]
Ahi lo revisé, faltaba agregarlo en el title del template y ya lo hice, pero sigue faltando en los resultados de búsqueda:
http://beta.policrowd.org/search?q=Gustavo+Esteban+GONZALEZ

Y quizás en otros lados.

BTW: Ahora estoy modificando los archivos en el template que está en elections/ar_policrowd_2016 y ya no quisiera tocar más los templates generales, para facilitar el merge en algún punto pero también para ordenar un poco los archivos.

**Comment by martinszy** [comment]
Se cambió para un lado y para el otro, ya funciona pero voy a esperar a que esté terminado para cerrar el issue.

**Comment by martinszy** [comment]
Ya esta bien.
Requiere cambiar los simplepopolofields en el admin: agregar givenname y family name y quitar name.
