### ISSUE TITLE
Problema agregando un puesto nuevo

### ISSUE THREAD

**Issue by martinszy** [ConocimientoAbierto/policrowd#13]
No se puede agregar un puesto, ya que este no se puede asociar a una organización.

Pasos para reproducir:
1) editar un politico, ej:
http://beta.policrowd.org/person/2253/update
2) Click en "agregar puesto"
3) Seleccionar un area que no tenga organizaciones, ej "Ciudad de bsas"
4) Agregar un puesto nuevo, ej "Jefe de Gobierno"
5) Agregar fechas de incio y finalización
6) Hacer click en "guardar"

Resultado:
Se recibe un menasje de error: "¡Epa!
No pudimos aceptar algunos de los cambios que hiciste.
Por favor verificá que tu información cumple con nuestros requerimientos, a continuación."

Resultado esperado:
Agregar un nuevo puesto y organización asociados a la ciudad de buenos aires.

**Comment by cesuarez** [comment]
Tengo entendido que los puestos solo tienen sentido crearlos si existe una organización a la cual vas a ocupar un puesto, por eso es obligatorio tener una organización.
Si ésto no es así, por favor comentame lo mas detalladamente posible como te gustaría que quede

**Comment by martinszy** [comment]
Cristian, hay dos problemas con esto:
1) No se puede agregar un puesto si la organización no existe... pero la interfaz no avisa de esto.
2) No hay forma de crear organizaciones ??

**Comment by cesuarez** [comment]
- 1) No se puede agregar un puesto si la organización no existe... pero la interfaz no avisa de esto.
  
  En realidad si te avisa, solo que cuando mandas el post del form y vuelve con el error, tenes que volver a abrir el formulario para agregar puesto, y vas a ver el error sobre el campo organizacion
- 2) No hay forma de crear organizaciones ??
  
  No, no hay forma de crear organizaciones.

**Comment by martinszy** [comment]
1) Ok, entonces será cuestión de que me encargue de mejorar la interfaz.
2) Desde el backend tendría que crearlas? Va a ser un problema esto si hay que crearlas a mano para todas las provincias y ciudades...

**Comment by godiard** [comment]
Lo mas práctico va a ser armar un csv como el de nación, e importarlas.
Otra alterntiva es agregar alguna organizacion "Otras" y que luego el administrador corrija.

**Comment by martinszy** [comment]
Estoy intentando crearlas desde el admin y no hay manera de asociar una organizacion como dentro de otra organización.
Editar a mano en el admin va a tener que ser posible, más allá del modo en que elijamos importar todos los poderes para todas las provincias.

**Comment by godiard** [comment]
Le estas poniendo el parent id?

**Comment by martinszy** [comment]
Esa propiedad no se expone en el admin.

**Comment by martinszy** [comment]
Ahora ceamos organizaciones para todas las ciudades y provincias, entonces hay forma de cargar un cargo aunque no sepamos la estructura de organizaciones de esa provincia.
