### ISSUE TITLE
Every post/role has to have start-date and end-date

### ISSUE THREAD

**Issue by rusosnith** [ConocimientoAbierto/policrowd#16]
Regardless if there will be an option to store previous posts/roles, the actual role has to have an starting date and a probable end date, just in case the politician resigns or changes role before the database gets updated.

**Comment by martinszy** [comment]
There are fields for that in the database and can be changed in the admin, and it's exposed in the interface in some parts, but it's not properly filled for some of the people in the db.
Will see if I can mass-update it to fix it.

**Comment by martinszy** [comment]
Fixed.
