### ISSUE TITLE
Nuevo campo Partido Político

### ISSUE THREAD

**Issue by manujas** [ConocimientoAbierto/policrowd#27]
Incorporar un nuevo campo a los políticos que indique su afiliación partidaria.

**Comment by martinszy** [comment]
Esto lo debe hacer el administrador, no requiere programación.

Idea: hacer una migración que genere los cambios básicos que le hacemos a
una instancia, sería otro issue.

**Comment by martinszy** [comment]
Ahora que pienso: Quizás los partidos son instituciones y la pertenencia un membership, ya que estas pueden variar con el tiempo. Aunque esto lo haría demasiado complejo.

**Comment by martinszy** [comment]
Por ahora agregué el campo partido como un texto libre, pero en el futuro podríamos evaluar cargar listas de partidos y crear memberships con fecha de inicio y fin.
