### ISSUE TITLE
Allow edit present or past positions for a Politician

### ISSUE THREAD

**Issue by martinszy** [ConocimientoAbierto/policrowd#7]
A candidate can participate in older elections if the elections are created in the site so we know when they were candidates and weather they won that election.
Same for nominations, a candidate can have a nomination that has already ended.

Related to https://github.com/mysociety/yournextrepresentative/issues/663

Part of #1 

Copied from https://github.com/mysociety/yournextrepresentative/issues/703

**Comment by godiard** [comment]
Vamos a agregar un nuevo modelo Politician, que es hijo de Person. 

Para cargar los puestos pasados o presentes, vamos a agregar una nueva Membersip. 
Organization: es el poder Ejecutivo, Legislativo o Judicial.
Area: es el area geografica
Post: es el cargo, Intendente, Diputado etc. (el Area nos provee la informacion adicional) 
Role: es un campo de texto libre, guardamos ahi el cargo si no está cargado previamente en la base.

NOTA: Actualmente en Post, se carga "Diputado Nacional por Formosa", con lo cual va a haber que modificar la generacion, y los datos actuales.

La UI en principio tiene una lógica similar a Linkedin, estamos cargando la historia de un político.

Un dato de la membership es el url del documento que es la fuente que valida el dato.

**Comment by martinszy** [comment]
No se puede verificar mientas no se solucionen los otros issues.

**Comment by martinszy** [comment]
Funcinoa, faltan algunos detalles, quizás abro otro issue.
