### ISSUE TITLE
Navegación en el site

### ISSUE THREAD

**Issue by godiard** [ConocimientoAbierto/policrowd#9]
Tenemos que definir como va a coexistir la información de los políticos con la de los candidatos.

Actualmente el sitio tiene un link "Provincias", que lista todas las provincias, y al seleccionar una, muestra todos los candidatos a la eleccion configurada en el site de esa provincia.

Una alternativa es tener en la home dos links "Políticos" y "Elecciones".
"Politicos" va al listado de "Provincias". Una vez selecccionada la provincia, se pueden ver los Políticos de la provincia, y un link a Municipios. 

"Elecciones" va al listado actual de provincias y sigue con las páginas ya existentes.
A futuro, "Elecciones" puede ir a una página que permita elegir entre múltiples elecciones existentes.

**Comment by martinszy** [comment]
Mi idea es que sean todas personas, algunas tendrían cargadas candidaturas y otras tendrían cargados cargos anteriores. Intentaría no segregar.
De todas formas creo que si vamos por provincia, podríamos poner todos los cargos y en cada cargo poner un enlace de "candidatos" y ahí se habilitaría la vista de todas las personas que fueron candidatos a ese cargo. En realidad debería haber un enlace a cada una de las elecciones que apunta a ese cargo (pueden haber varias elecciones de diferentes años para el mismo cargo).

¿Se entiende?

**Comment by godiard** [comment]
Está claro que son todas personas. Lo que sucede, es que cuando vas por la vista de candidaturas, estas relacionandolas con las elecciones, y cuando vas por la vista de políticos las relacionas por las áreas geográficas y sus organizaciones asociadas (poder ejecutivo, legislativo y judicial).

El objetivo de la propuesta, es tener que modificar lo mínimo posible lo que está funcionando actualmente, para no agregar más trabajo. Luego puede agregarse el manejo de múltiples elecciones que no está contemplado en el sitio actual de candidatos.

**Comment by martinszy** [comment]
Ok, esto esta resuelto.
